config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  namespace :api do
    namespace :v1 do
      resources :links
    end
  end
  resources :users, only: [:new]
  resources :links, only: [:create, :update]
  post '/signup', to: 'users#create'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'links#index'
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user

  def self.order_by(order_type)
    if order_type == 'alpha'
      order(title: :asc)
    elsif order_type == 'read_status'
      order(read_status: :asc)
    else
      order(created_at: :asc)
    end
  end

  def self.search_filter(search_term)
    if search_term != nil
      Link.where('title LIKE ?', "%#{search_term}%").all
    else
      Link.all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true,
                    uniqueness: true

  has_many :links
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::V1::BaseController
  def index
    respond_with current_user.links.search_filter(params[:search_term]).order_by(params[:order_type])
  end

  def create
    respond_with :api, :v1, current_user.links.create(link_params)
  end

  def update
    link = current_user.links.find(params["id"])
    link.update_attributes(link_params)
    respond_with link, json: link
  end

 private

  def link_params
    params.require(:link).permit(:title, :url, :read_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def create
    @link = current_user.links.new(link_params)
    if @link.save
      flash[:notice] = "Link Saved"
      redirect_to dashboard_path
    else
      flash[:notice] = "Invalid Link. Try again sucka."
      redirect_to dashboard_path
    end
  end

  def update
    @link = Link.find(params[:id])
    @link.update_read_status
    redirect_to dashboard_path
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:error] = "Invalid Login. Try Again."
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Logged in as #{@user.email}"
      redirect_to dashboard_path
    else
      flash[:notice] = "Invalid Login"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>
  <div class="container">

  <%= render partial: 'shared/flash_messages' %>
  <%= render partial: 'shared/nav' %>
  <%= yield %>

  </div>
</body>
</html>

app/views/links/_link.html.erb
<td><%= button_to('Edit', link_path(link.id), method: :put) %>
<td><%= link.title %></td>
<td><%= link.url %></td>
<td><%= link.read_status.capitalize %></td>
<td><%= button_to('Mark as Read', link_path(link.id), method: :put) %>

app/views/links/index.html.erb
<!-- <h1>Links</h1>
<h2>All Links</h2>
<table class="table">
  <tr>
    <td></td>
    <td>Title</td>
    <td>URL</td>
    <td>Read?</td>
    <td></td>
  </tr>
  <tr><%= render @links %></tr>
</table> -->

<%= react_component 'Main' %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <%= content_tag :div, msg %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Thoughtbox</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/user/new.html.erb
<h2>Create An Account</h2>
<%= form_for :user, url: signup_path do |f| %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/new.html.erb
<h2>Create An Account</h2>
<%= form_for :user, url: signup_path do |f| %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Create Account" %>

<% end %>

app/views/welcome/index.html.erb
<h1>Thoughtbox</h1>
<h2>Login</h2>
<%= form_for :session, url: login_path do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email%>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Login" %>
<% end %>

<h2>Don't Have an Account?</h2>
  <%= link_to('Sign Up', new_user_path) %>